name: FTP to Google Drive (daily)

on:
  schedule:
    - cron: '0 5 * * *'   # 05:00 UTC ≈ 07:00 Sverige
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Install rclone
        run: |
          sudo apt-get update -y
          sudo apt-get install -y rclone

      - name: Configure rclone remotes
        shell: bash
        run: |
          mkdir -p ~/.config/rclone
          # Obfuskera FTP-lösenordet så rclone accepterar det i conf
          FTP_PASS_OBSCURED=$(rclone obscure "${{ secrets.FTP_PASS }}")

          # Skriv rclone.conf (OBS: GDRIVE_TOKEN måste vara exakt JSON i en rad)
          cat > ~/.config/rclone/rclone.conf <<EOF
          [ftp]
          type = ftp
          host = ${{ secrets.FTP_HOST }}
          port = ${{ secrets.FTP_PORT }}
          user = ${{ secrets.FTP_USER }}
          pass = ${FTP_PASS_OBSCURED}

          [drive]
          type = drive
          token = ${{ secrets.GDRIVE_TOKEN }}
          EOF

          echo "===== rclone.conf (maskerat) ====="
          sed -E 's/(pass = ).*/\1***hidden***/; s/(token = ).*/\1***hidden***/' ~/.config/rclone/rclone.conf
          echo "=================================="

      - name: Testa listning (FTP)
        run: |
          SRC="ftp:/FromGenero/KivikDataExport/"
          rclone ls "$SRC" \
            --ftp-concurrency=1 \
            --ftp-disable-epsv \
            -vv \
            --timeout 5m \
            --contimeout 30s

      - name: Copy folder FTP → Google Drive (EPSV av)
        run: |
          SRC="ftp:/FromGenero/KivikDataExport/"
          DST="drive:/Kivik"
          rclone copy "$SRC" "$DST" \
            --progress \
            --transfers=1 \
            --ftp-concurrency=1 \
            --ftp-disable-epsv \
            --no-update-modtime \
            --retries 3 \
            --low-level-retries 10 \
            --timeout 10m \
            --contimeout 30s \
            --stats 30s -vv
