name: FTP to Google Drive (daily)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Install rclone
        run: |
          curl -fsSL https://rclone.org/install.sh | sudo bash
          rclone version

      - name: Configure rclone
        run: |
          mkdir -p ~/.config/rclone
          FTP_PASS_OBS=$(rclone obscure "${{ secrets.FTP_PASS }}")

          cat <<EOF > ~/.config/rclone/rclone.conf
[ftp]
type = ftp
host = ${{ secrets.FTP_HOST }}
port = ${{ secrets.FTP_PORT }}
user = ${{ secrets.FTP_USER }}
pass = $FTP_PASS_OBS
# explicit_tls = true   # Avkommentera om servern kräver FTPS

[drive]
type = drive
token = ${{ secrets.GDRIVE_TOKEN }}
EOF

          echo "✅ Konfiguration skapad."

      - name: Testa FTP-listning
        run: |
          rclone lsd "ftp:/FromGenero/KivikDataExport/" -vv --timeout 120s

      - name: Testa Google Drive-listning
        run: |
          rclone lsd "drive:/" -vv --timeout 60s

      - name: Kopiera FTP → Google Drive
        run: |
          rclone copy "ftp:/FromGenero/KivikDataExport/" "drive:/Kivik" \
            --transfers 1 \
            --checkers 2 \
            --no-update-modtime \
            --retries 3 \
            --low-level-retries 10 \
            --timeout 900s \
            --stats 30s -vv
