name: FTP to Google Drive (daily)

on:
  schedule:
    - cron: '0 5 * * *'   # 05:00 UTC ≈ 07:00 Sverige
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Install latest rclone
        run: |
          curl -fsSL https://rclone.org/install.sh | sudo bash
          rclone version

      - name: Configure rclone remotes
        shell: bash
        run: |
          mkdir -p ~/.config/rclone
          FTP_PASS_OBSCURED=$(rclone obscure "${{ secrets.FTP_PASS }}")
          cat > ~/.config/rclone/rclone.conf <<EOF
          [ftp]
          type = ftp
          host = ${{ secrets.FTP_HOST }}
          port = ${{ secrets.FTP_PORT }}
          user = ${{ secrets.FTP_USER }}
          pass = ${FTP_PASS_OBSCURED}

          [drive]
          type = drive
          token = ${{ secrets.GDRIVE_TOKEN }}
          EOF

          echo "===== rclone.conf (maskerat) ====="
          sed -E 's/(pass = ).*/\1***hidden***/; s/(token = ).*/\1***hidden***/' ~/.config/rclone/rclone.conf
          echo "=================================="

      # Snabba sanity checks
      - name: Test list (FTP and Drive)
        run: |
          set -x
          rclone lsd ftp: -vv --timeout 2m --contimeout 20s
          rclone about drive: -vv || true

      # ISOLERA FTP: hämta EN liten fil till /tmp så vi vet att datakanalen funkar
      - name: FTP single-file smoke test → /tmp (PASV + skip_control_ip)
        run: |
          SRC="ftp:/FromGenero/KivikDataExport/"
          rclone copy "$SRC" /tmp \
            --include "Kivik_Appointment.csv" \
            --size-only \
            --transfers=1 \
            --ftp-concurrency=1 \
            --ftp-skip-control-ip=true \
            --timeout 3m \
            --contimeout 20s \
            -vv

      # Huvudkörning – Försök 1: standard (EPSV/PASV) + skip_control_ip
      - name: Copy FTP → Google Drive [try #1: EPSV/PASV + skip_control_ip]
        id: copy1
        continue-on-error: true
        run: |
          SRC="ftp:/FromGenero/KivikDataExport/"
          DST="drive:/Kivik"
          rclone copy "$SRC" "$DST" \
            --progress \
            --transfers=1 \
            --checkers=2 \
            --no-update-modtime \
            --ftp-concurrency=1 \
            --ftp-skip-control-ip=true \
            --retries 3 \
            --low-level-retries 10 \
            --retries-sleep 10s \
            --timeout 10m \
            --contimeout 30s \
            --stats 30s -vv

      # Huvudkörning – Fallback: stäng av EPSV (vissa servrar kräver detta)
      - name: Copy FTP → Google Drive [try #2: disable EPSV]
        if: steps.copy1.outcome == 'failure'
        run: |
          SRC="ftp:/FromGenero/KivikDataExport/"
          DST="drive:/Kivik"
          rclone copy "$SRC" "$DST" \
            --progress \
            --transfers=1 \
            --checkers=2 \
            --no-update-modtime \
            --ftp-concurrency=1 \
            --ftp-disable-epsv \
            --ftp-skip-control-ip=true \
            --retries 3 \
            --low-level-retries 10 \
            --retries-sleep 10s \
            --timeout 10m \
            --contimeout 30s \
            --stats 30s -vv
