name: FTP to Google Drive (daily)

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Install latest rclone
        run: |
          curl -fsSL https://rclone.org/install.sh | sudo bash
          rclone version

      - name: Configure rclone remotes
        shell: bash
        run: |
          mkdir -p ~/.config/rclone
          FTP_PASS_OBSCURED=$(rclone obscure "${{ secrets.FTP_PASS }}")
          cat > ~/.config/rclone/rclone.conf <<EOF
          [ftp]
          type = ftp
          host = ${{ secrets.FTP_HOST }}
          port = ${{ secrets.FTP_PORT }}
          user = ${{ secrets.FTP_USER }}
          pass = ${FTP_PASS_OBSCURED}
          # Om servern kräver FTPS (explicit), avkommentera nästa rad:
          # explicit_tls = true

          [drive]
          type = drive
          token = ${{ secrets.GDRIVE_TOKEN }}
          EOF
          sed -E 's/(pass = ).*/\1***hidden***/; s/(token = ).*/\1***hidden***/' ~/.config/rclone/rclone.conf

      - name: Smoke test FTP (lista katalog)
        run: |
          rclone lsd ftp:/FromGenero/KivikDataExport/ -vv --timeout 2m --contimeout 20s

      - name: Kontroll: publik FTP (Tele2) – bör alltid fungera
        run: |
          rclone lsf :ftp: \
            --ftp-host=speedtest.tele2.net \
            --ftp-user=anonymous \
            --ftp-pass=$(rclone obscure dummy) \
            --max-depth 1 -vv --timeout 1m
        continue-on-error: true

      - name: Testa att hämta EN fil till /tmp (isolerar datakanal)
        run: |
          rclone copy ftp:/FromGenero/KivikDataExport/ /tmp \
            --include "Kivik_Appointment.csv" \
            --size-only --transfers=1 --checkers=1 \
            --timeout 3m --contimeout 20s -vv

      - name: Copy FTP → Google Drive (EPSV, default)
        run: |
          rclone copy ftp:/FromGenero/KivikDataExport/ drive:/Kivik \
            --progress \
            --transfers=1 --checkers=2 \
            --no-update-modtime \
            --retries 3 --low-level-retries 10 --retries-sleep 10s \
            --timeout 10m --contimeout 30s \
            --stats 30s -vv
