      - name: Configure rclone remotes
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install -y rclone
          mkdir -p ~/.config/rclone
          FTP_PASS_OBSCURED=$(rclone obscure "${{ secrets.FTP_PASS }}")
          cat > ~/.config/rclone/rclone.conf <<'EOF'
          [ftp]
          type = ftp
          host = ${{ secrets.FTP_HOST }}
          port = ${{ secrets.FTP_PORT }}
          user = ${{ secrets.FTP_USER }}
          pass = __FTP_PASS_OBSCURED__
          # Om servern strular med passive mode, test: disable_epsv = true
          # disable_epsv = true

          [drive]
          type = drive
          token = ${{ secrets.GDRIVE_TOKEN }}
          EOF
          # ersätt placeholdern med obscured-värdet
          sed -i "s|__FTP_PASS_OBSCURED__|$FTP_PASS_OBSCURED|g" ~/.config/rclone/rclone.conf

      # --- VÄLJ EN AV NEDAN (lämna EN aktiv) ---

      # 1) Kopiera HELA mappen på FTP → Google Drive
      - name: Copy folder FTP → Google Drive
        run: |
          rclone copy "ftp:/FromGenero/KivikDataExport/" "drive:/Kivik" --progress --transfers=1 --ftp-concurrency=1 --no-update-modtime
          # Om anslutningen strular, testa att lägga till flaggan:
          # --ftp-disable-epsv

      # 2) ENDAST CSV i mappen
      # - name: Copy only CSV
      #   run: |
      #     rclone copy "ftp:/FromGenero/KivikDataExport/" "drive:/Kivik" --include "*.csv" --progress --transfers=1 --ftp-concurrency=1 --no-update-modtime

      # 3) EN specifik fil
      # - name: Copy single file
      #   run: |
      #     rclone copy "ftp:/FromGenero/KivikDataExport/Kivik_Campaigns.csv" "drive:/Kivik" --progress --transfers=1 --ftp-concurrency=1 --no-update-modtime
