name: FTP to Google Drive (daily)

on:
  schedule:
    - cron: '0 5 * * *'   # 05:00 UTC ≈ 07:00 i Sverige
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Configure rclone remotes
        run: |
          mkdir -p ~/.config/rclone
          {
            echo "[ftp]"
            echo "type = ftp"
            echo "host = ${{ secrets.FTP_HOST }}"
            echo "port = ${{ secrets.FTP_PORT }}"
            echo "user = ${{ secrets.FTP_USER }}"
            echo "pass = ${{ secrets.FTP_PASS }}"
            echo ""
            echo "[drive]"
            echo "type = drive"
            echo "token = ${{ secrets.GDRIVE_TOKEN }}"
          } > ~/.config/rclone/rclone.conf

      - name: Copy only CSV
        run: |
          rclone copy "ftp:/FromGenero/KivikDataExport/" "drive:/Kivik" --include "*.csv" --progress --transfers=1 --ftp-concurrency=1 --no-update-modtime

