name: FTP to Google Drive (daily)

on:
  schedule:
    - cron: '0 5 * * *'   # 05:00 UTC ≈ 07:00 Sverige
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Install rclone
        run: |
          sudo apt-get update -y
          sudo apt-get install -y rclone

      - name: Configure rclone remotes
        shell: bash
        run: |
          mkdir -p ~/.config/rclone
          FTP_PASS_OBSCURED=$(rclone obscure "${{ secrets.FTP_PASS }}")

          cat > ~/.config/rclone/rclone.conf <<EOF
          [ftp]
          type = ftp
          host = ${{ secrets.FTP_HOST }}
          port = ${{ secrets.FTP_PORT }}
          user = ${{ secrets.FTP_USER }}
          pass = __FTP_PASS_OBSCURED__

          [drive]
          type = drive
          token = ${{ secrets.GDRIVE_TOKEN }}
          EOF

          sed -i "s|__FTP_PASS_OBSCURED__|$FTP_PASS_OBSCURED|g" ~/.config/rclone/rclone.conf

          echo "===== rclone.conf ====="
          sed 's/pass = .*/pass = ***hidden***/' ~/.config/rclone/rclone.conf
          echo "======================="

      - name: Copy folder FTP → Google Drive
        run: |
          # Ändra källsökvägen här om din FTP-mapp skiljer sig
          SRC="ftp:/FromGenero/KivikDataExport/"
          DST="drive:/Kivik"

          # Kör kopieringen (binärt, bevarar å/ä/ö)
          rclone copy "$SRC" "$DST" \
            --progress \
            --transfers=1 \
            --ftp-concurrency=1 \
            --no-update-modtime \
            --retries 3 \
            --low-level-retries 10
            # Om FTP-strular med passivt läge, lägg till:
            # --ftp-disable-epsv
